### ISSUE TITLE
Could not locate dev__init.class, dev.clj or dev.cljc on classpath

### ISSUE THREAD

**Issue by malcolmsparks** [juxt/edge#60]
Error on new cljs app.

```
[malcolm@melkor edge]$ bin/app acme/app --sass --cljs
Generating fresh 'clj new' edge.app-template project into acme.app.
[malcolm@melkor edge]$ cd acme.app/
[malcolm@melkor acme.app]$ ../bin/rebel --nrepl --cljs
[Edge] Starting development environment, please wait…
[Rebel readline] Type :repl/help for online help info
[Edge] Loading Clojure code, please wait...
java.io.FileNotFoundException: Could not locate dev__init.class, dev.clj or dev.cljc on classpath.
	at clojure.lang.RT.load(RT.java:466)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at edge.rebel.main$_main$fn__2891.invoke(main.clj:59)
	at clojure.main$repl$fn__9075.invoke(main.clj:427)
	at clojure.main$repl.invokeStatic(main.clj:426)
	at clojure.main$repl.doInvoke(main.clj:345)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at rebel_readline.clojure.main$eval2756$repl_STAR___2757.invoke(main.clj:82)
	at rebel_readline.clojure.main$repl.invokeStatic(main.clj:91)
	at rebel_readline.clojure.main$repl.doInvoke(main.clj:90)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at edge.rebel.main$_main.invokeStatic(main.clj:55)
	at edge.rebel.main$_main.doInvoke(main.clj:52)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
[Edge] Failed to require dev, this usually means there was a syntax error. See exception above.
[Edge] Please correct it, and enter (fixed!) to resume development.
user=> 

```

**Comment by SevereOverfl0w** [comment]
../bin/rebel requires that you have a dev.clj on your classpath, so you need to supply aliases to make that happen, e.g. `-A:dev`

**Comment by SevereOverfl0w** [comment]
I've improved the message when this happens:

![maim-2019-02-25-10 05 45](https://user-images.githubusercontent.com/6136282/53329903-2327fc00-38e5-11e9-9d62-48e117752169.png)
